name: Deploy to App Servers

on:
  push:
    branches:
      - main   # Change if you want another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Deploy to App Server 1
      - name: Deploy to App Server 1
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html/native-php-app-master || exit 1
            git pull origin main
            echo "✅ Deployment done on App Server 1"

      # Deploy to App Server 2
      - name: Deploy to App Server 2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST_SERVER2 }}
          username: ${{ secrets.EC2_USER_SERVER2 }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html/native-php-app-master || exit 1
            git pull origin main
            echo "✅ Deployment done on App Server 2"
