name: Deploy to EC2 Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Deploy to Server 1
      - name: Deploy to EC2 Server 1
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST1 }}
          username: ${{ secrets.EC2_USER1 }}
          key: ${{ secrets.EC2_SSH_KEY1 }}
          script: |
            cd /var/www/html/native-php-app-master || exit
            git fetch --all
            git reset --hard origin/main
            sudo chown -R www-data:www-data /var/www/html/native-php-app-master
            sudo systemctl restart apache2

      # Deploy to Server 2
      - name: Deploy to EC2 Server 2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST2 }}
          username: ${{ secrets.EC2_USER2 }}
          key: ${{ secrets.EC2_SSH_KEY2 }}
          script: |
            cd /var/www/html || exit
            git fetch --all
            git reset --hard origin/main
            sudo chown -R www-data:www-data /var/www/html
            sudo systemctl restart apache2
